{
  inputs,
  pkgs,
  pkgs-unstable,
  ...
}: {
  imports = [
    inputs.niri.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
  ];
  programs.niri = {
    enable = true;
    package = pkgs.niri;
    settings = {
      layout = {
        border = {
          enable = false;
        };
      };
    };
  };
  programs.dank-material-shell = {
    dgop.package = pkgs-unstable.dgop;
    enable = true;
    systemd = {
      enable = true; # Systemd service for auto-start
      restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
    };
    # Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    #enableVPN = true; # VPN management widget
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    #enableCalendarEvents = true; # Calendar integration (khal)
    enableClipboardPaste = true; # Pasting items from the clipboard (wtype)
    settings = {
      theme = "dark";
      dynamicTheming = true;
      # Add any other settings here
    };
    session = {
      isLightMode = false;
      # Add any other session state settings here
    };
    clipboardSettings = {
      maxHistory = 25;
      maxEntrySize = 5242880;
      autoClearDays = 1;
      clearAtStartup = true;
      disabled = false;
      disableHistory = false;
      disablePersist = true;
    };
    # niri = {
    #   enableKeybinds = false; # Sets static preset keybinds
    #   enableSpawn = false; # Auto-start DMS with niri, if enabled
    #   includes = {
    #     enable = true; # Enable config includes hack. Enabled by default.

    #     override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
    #     originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
    #     filesToInclude = [
    #       # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
    #       "alttab" # Please note that niri will throw an error if any of these files are missing.
    #       "binds"
    #       "colors"
    #       "layout"
    #       "outputs"
    #       "wpblur"
    #     ];
    #   };
    # };
  };
}
